scripts:
  - filename:	win_script.bat
    target_os:	windows
  - filename:	script.sh
    target_os:	linux
path_parameters:
  - input
  - xml_file
  - name
  - path
  - file
source_code_root: 'test_data'
ignore_patterns:
  global:
    - 'folder1'
    - 'folder2'
    - '*.md'
    - 'win_script.bat'
    - 'scriprt.sh'
  stylesheets_folder:
    - '*.txt'
logfile: execution.log