scripts:
  - filename:	DeploymentInstructions.bat
    target_os:	windows
  - filename:	DeploymentInstructions.sh_
    target_os:	linux
path_parameters:
  - input
  - xml_file
  - name
  - path
  - file
source_code_root: test_data
ignore_patterns:
  - "*.tst"
  - "*.bat*"
  - creds*
logfile: execution.log
